import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import { faces } from '../public/db';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kxffiehub.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.test}>Test</h1>

        <div className={styles.row}>
          {faces.map((faces) => (
            <div key="faces" className={styles.column} onClick={() =>  navigator.clipboard.writeText(faces.face)}>
              <div className={styles.card}>{faces.face}</div>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
